// AUTO-GENERATED by scripts/codegen.ts — edits will be overwritten

enum Role {
  warga("WARGA"),
  surveyor("SURVEYOR"),
  verifikator("VERIFIKATOR"),
  operator("OPERATOR"),
  petugas("PETUGAS"),
  pengambilKeputusan("PENGAMBIL_KEPUTUSAN"),
  adminDaerah("ADMIN_DAERAH"),
  auditor("AUDITOR"),
  rtRw("RT_RW"),
  admin("ADMIN");
  final String value;
  const Role(this.value);
  static const allValues = <Role>[Role.warga, Role.surveyor, Role.verifikator, Role.operator, Role.petugas, Role.pengambilKeputusan, Role.adminDaerah, Role.auditor, Role.rtRw, Role.admin];
  static Role fromJson(String value) => allValues.firstWhere((e) => e.value == value);
}

enum ReportStatus {
  submitted("submitted"),
  underReview("under_review"),
  verified("verified"),
  inProgress("in_progress"),
  resolved("resolved"),
  rejected("rejected"),
  duplicateMerged("duplicate_merged"),
  needsSurvey("needs_survey");
  final String value;
  const ReportStatus(this.value);
  static const allValues = <ReportStatus>[ReportStatus.submitted, ReportStatus.underReview, ReportStatus.verified, ReportStatus.inProgress, ReportStatus.resolved, ReportStatus.rejected, ReportStatus.duplicateMerged, ReportStatus.needsSurvey];
  static ReportStatus fromJson(String value) => allValues.firstWhere((e) => e.value == value);
}

enum AssessmentStatus {
  completed("completed"),
  timeout("timeout"),
  parseFailed("parse_failed"),
  vlmError("vlm_error");
  final String value;
  const AssessmentStatus(this.value);
  static const allValues = <AssessmentStatus>[AssessmentStatus.completed, AssessmentStatus.timeout, AssessmentStatus.parseFailed, AssessmentStatus.vlmError];
  static AssessmentStatus fromJson(String value) => allValues.firstWhere((e) => e.value == value);
}

class User {
  final String id;
  final String email;
  final Role role;
  final String name;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;
  User({required this.id, required this.email, required this.role, required this.name, required this.createdAt, required this.updatedAt, this.deletedAt});

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] as String,
      email: json['email'] as String,
      role: Role.fromJson(json['role'] as String),
      name: json['name'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      deletedAt: json['deleted_at'] != null ? DateTime.parse(json['deleted_at'] as String) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'role': role.value,
      'name': name,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
      'deleted_at': deletedAt?.toIso8601String(),
    };
  }
}

class Category {
  final String id;
  final String slug;
  final String name;
  final String? icon;
  final DateTime createdAt;
  Category({required this.id, required this.slug, required this.name, this.icon, required this.createdAt});

  factory Category.fromJson(Map<String, dynamic> json) {
    return Category(
      id: json['id'] as String,
      slug: json['slug'] as String,
      name: json['name'] as String,
      icon: json['icon'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'slug': slug,
      'name': name,
      'icon': icon,
      'created_at': createdAt.toIso8601String(),
    };
  }
}

class Wilayah {
  final String id;
  final String? parentId;
  final String name;
  final String level;
  final Map<String, dynamic>? geom;
  final DateTime createdAt;
  Wilayah({required this.id, this.parentId, required this.name, required this.level, this.geom, required this.createdAt});

  factory Wilayah.fromJson(Map<String, dynamic> json) {
    return Wilayah(
      id: json['id'] as String,
      parentId: json['parent_id'] as String?,
      name: json['name'] as String,
      level: json['level'] as String,
      geom: json['geom'] as Map<String, dynamic>?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'parent_id': parentId,
      'name': name,
      'level': level,
      'geom': geom,
      'created_at': createdAt.toIso8601String(),
    };
  }
}

class Report {
  final String id;
  final String idempotencyKey;
  final String categoryId;
  final Category? category;
  final String description;
  final Map<String, dynamic>? geom;
  final double lat;
  final double lng;
  final List<String>? photoUrls;
  final Map<String, dynamic>? exifData;
  final String? deviceId;
  final ReportStatus status;
  final int? severity;
  final String? assignedTo;
  final User? assignee;
  final DateTime createdAt;
  final DateTime updatedAt;
  Report({required this.id, required this.idempotencyKey, required this.categoryId, this.category, required this.description, this.geom, required this.lat, required this.lng, this.photoUrls, this.exifData, this.deviceId, required this.status, this.severity, this.assignedTo, this.assignee, required this.createdAt, required this.updatedAt});

  factory Report.fromJson(Map<String, dynamic> json) {
    return Report(
      id: json['id'] as String,
      idempotencyKey: json['idempotency_key'] as String,
      categoryId: json['category_id'] as String,
      category: json['category'] != null ? Category.fromJson(json['category'] as Map<String, dynamic>) : null,
      description: json['description'] as String,
      geom: json['geom'] as Map<String, dynamic>?,
      lat: (json['lat'] as num).toDouble(),
      lng: (json['lng'] as num).toDouble(),
      photoUrls: (json['photo_urls'] as List?)?.map((e) => e as String).toList(),
      exifData: json['exif_data'] as Map<String, dynamic>?,
      deviceId: json['device_id'] as String?,
      status: ReportStatus.fromJson(json['status'] as String),
      severity: json['severity'] as int?,
      assignedTo: json['assigned_to'] as String?,
      assignee: json['assignee'] != null ? User.fromJson(json['assignee'] as Map<String, dynamic>) : null,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'idempotency_key': idempotencyKey,
      'category_id': categoryId,
      'category': category?.toJson(),
      'description': description,
      'geom': geom,
      'lat': lat,
      'lng': lng,
      'photo_urls': photoUrls,
      'exif_data': exifData,
      'device_id': deviceId,
      'status': status.value,
      'severity': severity,
      'assigned_to': assignedTo,
      'assignee': assignee?.toJson(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

class CreateReportRequest {
  final String idempotencyKey;
  final String categoryId;
  final String description;
  final double lat;
  final double lng;
  final List<String>? photoUrls;
  final Map<String, dynamic>? exifData;
  final String? deviceId;
  CreateReportRequest({required this.idempotencyKey, required this.categoryId, required this.description, required this.lat, required this.lng, this.photoUrls, this.exifData, this.deviceId});

  factory CreateReportRequest.fromJson(Map<String, dynamic> json) {
    return CreateReportRequest(
      idempotencyKey: json['idempotency_key'] as String,
      categoryId: json['category_id'] as String,
      description: json['description'] as String,
      lat: (json['lat'] as num).toDouble(),
      lng: (json['lng'] as num).toDouble(),
      photoUrls: (json['photo_urls'] as List?)?.map((e) => e as String).toList(),
      exifData: json['exif_data'] as Map<String, dynamic>?,
      deviceId: json['device_id'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'idempotency_key': idempotencyKey,
      'category_id': categoryId,
      'description': description,
      'lat': lat,
      'lng': lng,
      'photo_urls': photoUrls,
      'exif_data': exifData,
      'device_id': deviceId,
    };
  }
}

class UpdateReportRequest {
  final ReportStatus? status;
  final int? severity;
  final String? assignedTo;
  UpdateReportRequest({this.status, this.severity, this.assignedTo});

  factory UpdateReportRequest.fromJson(Map<String, dynamic> json) {
    return UpdateReportRequest(
      status: json['status'] != null ? ReportStatus.fromJson(json['status'] as String) : null,
      severity: json['severity'] as int?,
      assignedTo: json['assigned_to'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'status': status?.value,
      'severity': severity,
      'assigned_to': assignedTo,
    };
  }
}

class AgentAssessment {
  final String id;
  final String reportId;
  final String assessmentKind;
  final AssessmentStatus assessmentStatus;
  final String? visionDescription;
  final int? damageSeverity;
  final Map<String, dynamic>? exifSummary;
  final List<Map<String, dynamic>>? duplicateCandidates;
  final double? confidence;
  final ReportStatus? recommendedStatus;
  final int? toolCallsMade;
  final int? latencyMs;
  final String? modelVersion;
  final DateTime createdAt;
  AgentAssessment({required this.id, required this.reportId, required this.assessmentKind, required this.assessmentStatus, this.visionDescription, this.damageSeverity, this.exifSummary, this.duplicateCandidates, this.confidence, this.recommendedStatus, this.toolCallsMade, this.latencyMs, this.modelVersion, required this.createdAt});

  factory AgentAssessment.fromJson(Map<String, dynamic> json) {
    return AgentAssessment(
      id: json['id'] as String,
      reportId: json['report_id'] as String,
      assessmentKind: json['assessment_kind'] as String,
      assessmentStatus: AssessmentStatus.fromJson(json['assessment_status'] as String),
      visionDescription: json['vision_description'] as String?,
      damageSeverity: json['damage_severity'] as int?,
      exifSummary: json['exif_summary'] as Map<String, dynamic>?,
      duplicateCandidates: (json['duplicate_candidates'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      confidence: (json['confidence'] as num?)?.toDouble(),
      recommendedStatus: json['recommended_status'] != null ? ReportStatus.fromJson(json['recommended_status'] as String) : null,
      toolCallsMade: json['tool_calls_made'] as int?,
      latencyMs: json['latency_ms'] as int?,
      modelVersion: json['model_version'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'report_id': reportId,
      'assessment_kind': assessmentKind,
      'assessment_status': assessmentStatus.value,
      'vision_description': visionDescription,
      'damage_severity': damageSeverity,
      'exif_summary': exifSummary,
      'duplicate_candidates': duplicateCandidates,
      'confidence': confidence,
      'recommended_status': recommendedStatus?.value,
      'tool_calls_made': toolCallsMade,
      'latency_ms': latencyMs,
      'model_version': modelVersion,
      'created_at': createdAt.toIso8601String(),
    };
  }
}

class LoginRequest {
  final String email;
  final String password;
  LoginRequest({required this.email, required this.password});

  factory LoginRequest.fromJson(Map<String, dynamic> json) {
    return LoginRequest(
      email: json['email'] as String,
      password: json['password'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'email': email,
      'password': password,
    };
  }
}

class LoginResponse {
  final String accessToken;
  final String refreshToken;
  final int expiresIn;
  final User? user;
  LoginResponse({required this.accessToken, required this.refreshToken, required this.expiresIn, this.user});

  factory LoginResponse.fromJson(Map<String, dynamic> json) {
    return LoginResponse(
      accessToken: json['access_token'] as String,
      refreshToken: json['refresh_token'] as String,
      expiresIn: json['expires_in'] as int,
      user: json['user'] != null ? User.fromJson(json['user'] as Map<String, dynamic>) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'access_token': accessToken,
      'refresh_token': refreshToken,
      'expires_in': expiresIn,
      'user': user?.toJson(),
    };
  }
}

class ErrorResponse {
  final String error;
  final String? detail;
  ErrorResponse({required this.error, this.detail});

  factory ErrorResponse.fromJson(Map<String, dynamic> json) {
    return ErrorResponse(
      error: json['error'] as String,
      detail: json['detail'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'error': error,
      'detail': detail,
    };
  }
}

class GeoJSONFeatureCollection {
  final String type;
  final List<GeoJSONFeature> features;
  GeoJSONFeatureCollection({required this.type, required this.features});

  factory GeoJSONFeatureCollection.fromJson(Map<String, dynamic> json) {
    return GeoJSONFeatureCollection(
      type: json['type'] as String,
      features: (json['features'] as List?)?.map((e) => GeoJSONFeature.fromJson(e as Map<String, dynamic>)).toList() ?? [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'type': type,
      'features': features,
    };
  }
}

class GeoJSONFeature {
  final String type;
  final Map<String, dynamic> geometry;
  final Map<String, dynamic> properties;
  GeoJSONFeature({required this.type, required this.geometry, required this.properties});

  factory GeoJSONFeature.fromJson(Map<String, dynamic> json) {
    return GeoJSONFeature(
      type: json['type'] as String,
      geometry: json['geometry'] as Map<String, dynamic>,
      properties: json['properties'] as Map<String, dynamic>,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'type': type,
      'geometry': geometry,
      'properties': properties,
    };
  }
}

class GeoJSONPoint {
  final String type;
  final List<double> coordinates;
  GeoJSONPoint({required this.type, required this.coordinates});

  factory GeoJSONPoint.fromJson(Map<String, dynamic> json) {
    return GeoJSONPoint(
      type: json['type'] as String,
      coordinates: (json['coordinates'] as List?)?.map((e) => (e as num).toDouble()).toList() ?? [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'type': type,
      'coordinates': coordinates,
    };
  }
}

class GeoJSONPolygon {
  final String type;
  final List<List<List<double>>> coordinates;
  GeoJSONPolygon({required this.type, required this.coordinates});

  factory GeoJSONPolygon.fromJson(Map<String, dynamic> json) {
    return GeoJSONPolygon(
      type: json['type'] as String,
      coordinates: (json['coordinates'] as List?)?.map((e) => (e as List).map((e) => (e as List).map((e) => (e as num).toDouble()).toList()).toList()).toList() ?? [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'type': type,
      'coordinates': coordinates,
    };
  }
}
