// AUTO-GENERATED by scripts/codegen.ts — edits will be overwritten

enum ReportStatus {
  draft("draft"),
  submitted("submitted"),
  underReview("under_review"),
  verified("verified"),
  assigned("assigned"),
  inProgress("in_progress"),
  resolved("resolved"),
  closed("closed"),
  rejected("rejected"),
  duplicateMerged("duplicate_merged"),
  needsSurvey("needs_survey"),
  merged("merged"),
  separated("separated"),
  needsCompletion("needs_completion"),
  outOfScope("out_of_scope");
  final String value;
  const ReportStatus(this.value);
  static const allValues = <ReportStatus>[ReportStatus.draft, ReportStatus.submitted, ReportStatus.underReview, ReportStatus.verified, ReportStatus.assigned, ReportStatus.inProgress, ReportStatus.resolved, ReportStatus.closed, ReportStatus.rejected, ReportStatus.duplicateMerged, ReportStatus.needsSurvey, ReportStatus.merged, ReportStatus.separated, ReportStatus.needsCompletion, ReportStatus.outOfScope];
  static ReportStatus fromJson(String value) => allValues.firstWhere((e) => e.value == value);
}

enum Priority {
  low("low"),
  medium("medium"),
  high("high"),
  critical("critical");
  final String value;
  const Priority(this.value);
  static const allValues = <Priority>[Priority.low, Priority.medium, Priority.high, Priority.critical];
  static Priority fromJson(String value) => allValues.firstWhere((e) => e.value == value);
}

class ErrorResponse {
  final String? error;
  final List<Map<String, dynamic>>? details;
  ErrorResponse({this.error, this.details});

  factory ErrorResponse.fromJson(Map<String, dynamic> json) {
    return ErrorResponse(
      error: json['error'] as String?,
      details: (json['details'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'error': error,
      'details': details,
    };
  }
}

class Pagination {
  final int? page;
  final int? limit;
  final int? total;
  final int? totalPages;
  Pagination({this.page, this.limit, this.total, this.totalPages});

  factory Pagination.fromJson(Map<String, dynamic> json) {
    return Pagination(
      page: json['page'] as int?,
      limit: json['limit'] as int?,
      total: json['total'] as int?,
      totalPages: json['total_pages'] as int?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'page': page,
      'limit': limit,
      'total': total,
      'total_pages': totalPages,
    };
  }
}

class Photo {
  final String? id;
  final String? url;
  final String? thumbnailUrl;
  final String? uploadedAt;
  Photo({this.id, this.url, this.thumbnailUrl, this.uploadedAt});

  factory Photo.fromJson(Map<String, dynamic> json) {
    return Photo(
      id: json['id'] as String?,
      url: json['url'] as String?,
      thumbnailUrl: json['thumbnailUrl'] as String?,
      uploadedAt: json['uploadedAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'url': url,
      'thumbnailUrl': thumbnailUrl,
      'uploadedAt': uploadedAt,
    };
  }
}

class TimelineEvent {
  final String? id;
  final String? type;
  final String? message;
  final String? timestamp;
  final String? userId;
  TimelineEvent({this.id, this.type, this.message, this.timestamp, this.userId});

  factory TimelineEvent.fromJson(Map<String, dynamic> json) {
    return TimelineEvent(
      id: json['id'] as String?,
      type: json['type'] as String?,
      message: json['message'] as String?,
      timestamp: json['timestamp'] as String?,
      userId: json['userId'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'type': type,
      'message': message,
      'timestamp': timestamp,
      'userId': userId,
    };
  }
}

class Notification {
  final String? id;
  final String? title;
  final String? body;
  final bool? read;
  final String? createdAt;
  Notification({this.id, this.title, this.body, this.read, this.createdAt});

  factory Notification.fromJson(Map<String, dynamic> json) {
    return Notification(
      id: json['id'] as String?,
      title: json['title'] as String?,
      body: json['body'] as String?,
      read: json['read'] as bool?,
      createdAt: json['createdAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'body': body,
      'read': read,
      'createdAt': createdAt,
    };
  }
}

class OutboxEntry {
  final String? id;
  final String? event;
  final Map<String, dynamic>? payload;
  final String? status;
  final int? attempts;
  final String? lastAttempt;
  final String? createdAt;
  OutboxEntry({this.id, this.event, this.payload, this.status, this.attempts, this.lastAttempt, this.createdAt});

  factory OutboxEntry.fromJson(Map<String, dynamic> json) {
    return OutboxEntry(
      id: json['id'] as String?,
      event: json['event'] as String?,
      payload: json['payload'] as Map<String, dynamic>?,
      status: json['status'] as String?,
      attempts: json['attempts'] as int?,
      lastAttempt: json['lastAttempt'] as String?,
      createdAt: json['createdAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'event': event,
      'payload': payload,
      'status': status,
      'attempts': attempts,
      'lastAttempt': lastAttempt,
      'createdAt': createdAt,
    };
  }
}

class AuditEntry {
  final String? id;
  final String? userId;
  final String? action;
  final String? resource;
  final String? resourceId;
  final Map<String, dynamic>? metadata;
  final String? timestamp;
  AuditEntry({this.id, this.userId, this.action, this.resource, this.resourceId, this.metadata, this.timestamp});

  factory AuditEntry.fromJson(Map<String, dynamic> json) {
    return AuditEntry(
      id: json['id'] as String?,
      userId: json['userId'] as String?,
      action: json['action'] as String?,
      resource: json['resource'] as String?,
      resourceId: json['resourceId'] as String?,
      metadata: json['metadata'] as Map<String, dynamic>?,
      timestamp: json['timestamp'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'action': action,
      'resource': resource,
      'resourceId': resourceId,
      'metadata': metadata,
      'timestamp': timestamp,
    };
  }
}

class Category {
  final String? id;
  final String? name;
  final String? icon;
  final int? reportCount;
  Category({this.id, this.name, this.icon, this.reportCount});

  factory Category.fromJson(Map<String, dynamic> json) {
    return Category(
      id: json['id'] as String?,
      name: json['name'] as String?,
      icon: json['icon'] as String?,
      reportCount: json['reportCount'] as int?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'icon': icon,
      'reportCount': reportCount,
    };
  }
}

class Unit {
  final String? id;
  final String? name;
  final String? type;
  final String? region;
  Unit({this.id, this.name, this.type, this.region});

  factory Unit.fromJson(Map<String, dynamic> json) {
    return Unit(
      id: json['id'] as String?,
      name: json['name'] as String?,
      type: json['type'] as String?,
      region: json['region'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'type': type,
      'region': region,
    };
  }
}

class SlaConfig {
  final String? id;
  final String? name;
  final int? slaDays;
  final Priority? priority;
  final bool? isActive;
  final String? createdAt;
  SlaConfig({this.id, this.name, this.slaDays, this.priority, this.isActive, this.createdAt});

  factory SlaConfig.fromJson(Map<String, dynamic> json) {
    return SlaConfig(
      id: json['id'] as String?,
      name: json['name'] as String?,
      slaDays: json['slaDays'] as int?,
      priority: json['priority'] != null ? Priority.fromJson(json['priority'] as String) : null,
      isActive: json['isActive'] as bool?,
      createdAt: json['createdAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'slaDays': slaDays,
      'priority': priority?.value,
      'isActive': isActive,
      'createdAt': createdAt,
    };
  }
}

class ChecklistTemplate {
  final String? id;
  final String? name;
  final List<Map<String, dynamic>>? items;
  final String? createdAt;
  ChecklistTemplate({this.id, this.name, this.items, this.createdAt});

  factory ChecklistTemplate.fromJson(Map<String, dynamic> json) {
    return ChecklistTemplate(
      id: json['id'] as String?,
      name: json['name'] as String?,
      items: (json['items'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      createdAt: json['createdAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'items': items,
      'createdAt': createdAt,
    };
  }
}

class PriorityConfig {
  final String? id;
  final String? name;
  final List<Map<String, dynamic>>? rules;
  final bool? isActive;
  final String? createdAt;
  PriorityConfig({this.id, this.name, this.rules, this.isActive, this.createdAt});

  factory PriorityConfig.fromJson(Map<String, dynamic> json) {
    return PriorityConfig(
      id: json['id'] as String?,
      name: json['name'] as String?,
      rules: (json['rules'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      isActive: json['isActive'] as bool?,
      createdAt: json['createdAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'rules': rules,
      'isActive': isActive,
      'createdAt': createdAt,
    };
  }
}

class LoginRequest {
  final String email;
  final String password;
  LoginRequest({required this.email, required this.password});

  factory LoginRequest.fromJson(Map<String, dynamic> json) {
    return LoginRequest(
      email: json['email'] as String,
      password: json['password'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'email': email,
      'password': password,
    };
  }
}

class LoginResponse {
  final String? token;
  final String? refreshToken;
  final User? user;
  LoginResponse({this.token, this.refreshToken, this.user});

  factory LoginResponse.fromJson(Map<String, dynamic> json) {
    return LoginResponse(
      token: json['token'] as String?,
      refreshToken: json['refreshToken'] as String?,
      user: json['user'] != null ? User.fromJson(json['user'] as Map<String, dynamic>) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'token': token,
      'refreshToken': refreshToken,
      'user': user?.toJson(),
    };
  }
}

class User {
  final String? id;
  final String? email;
  final String? name;
  final String? role;
  final String? unitId;
  final String? createdAt;
  User({this.id, this.email, this.name, this.role, this.unitId, this.createdAt});

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] as String?,
      email: json['email'] as String?,
      name: json['name'] as String?,
      role: json['role'] as String?,
      unitId: json['unitId'] as String?,
      createdAt: json['createdAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'name': name,
      'role': role,
      'unitId': unitId,
      'createdAt': createdAt,
    };
  }
}

class UserResponse {
  final String? id;
  final String? email;
  final String? name;
  final String? role;
  final String? unitId;
  final String? createdAt;
  UserResponse({this.id, this.email, this.name, this.role, this.unitId, this.createdAt});

  factory UserResponse.fromJson(Map<String, dynamic> json) {
    return UserResponse(
      id: json['id'] as String?,
      email: json['email'] as String?,
      name: json['name'] as String?,
      role: json['role'] as String?,
      unitId: json['unitId'] as String?,
      createdAt: json['createdAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'name': name,
      'role': role,
      'unitId': unitId,
      'createdAt': createdAt,
    };
  }
}

class Report {
  final String? id;
  final String? title;
  final String? description;
  final String? category;
  final ReportStatus? status;
  final Priority? priority;
  final Map<String, dynamic>? location;
  final String? reporterId;
  final List<Photo>? photos;
  final String? slaDeadline;
  final String? createdAt;
  final String? updatedAt;
  Report({this.id, this.title, this.description, this.category, this.status, this.priority, this.location, this.reporterId, this.photos, this.slaDeadline, this.createdAt, this.updatedAt});

  factory Report.fromJson(Map<String, dynamic> json) {
    return Report(
      id: json['id'] as String?,
      title: json['title'] as String?,
      description: json['description'] as String?,
      category: json['category'] as String?,
      status: json['status'] != null ? ReportStatus.fromJson(json['status'] as String) : null,
      priority: json['priority'] != null ? Priority.fromJson(json['priority'] as String) : null,
      location: json['location'] as Map<String, dynamic>?,
      reporterId: json['reporterId'] as String?,
      photos: (json['photos'] as List?)?.map((e) => Photo.fromJson(e as Map<String, dynamic>)).toList(),
      slaDeadline: json['slaDeadline'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'category': category,
      'status': status?.value,
      'priority': priority?.value,
      'location': location,
      'reporterId': reporterId,
      'photos': photos,
      'slaDeadline': slaDeadline,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}

class ReportDetail {
  final String? id;
  final String? title;
  final String? description;
  final String? category;
  final ReportStatus? status;
  final Priority? priority;
  final Map<String, dynamic>? location;
  final String? reporterId;
  final List<Photo>? photos;
  final List<Map<String, dynamic>>? assessments;
  final List<Map<String, dynamic>>? visits;
  final String? slaDeadline;
  final String? createdAt;
  final String? updatedAt;
  ReportDetail({this.id, this.title, this.description, this.category, this.status, this.priority, this.location, this.reporterId, this.photos, this.assessments, this.visits, this.slaDeadline, this.createdAt, this.updatedAt});

  factory ReportDetail.fromJson(Map<String, dynamic> json) {
    return ReportDetail(
      id: json['id'] as String?,
      title: json['title'] as String?,
      description: json['description'] as String?,
      category: json['category'] as String?,
      status: json['status'] != null ? ReportStatus.fromJson(json['status'] as String) : null,
      priority: json['priority'] != null ? Priority.fromJson(json['priority'] as String) : null,
      location: json['location'] as Map<String, dynamic>?,
      reporterId: json['reporterId'] as String?,
      photos: (json['photos'] as List?)?.map((e) => Photo.fromJson(e as Map<String, dynamic>)).toList(),
      assessments: (json['assessments'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      visits: (json['visits'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      slaDeadline: json['slaDeadline'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'category': category,
      'status': status?.value,
      'priority': priority?.value,
      'location': location,
      'reporterId': reporterId,
      'photos': photos,
      'assessments': assessments,
      'visits': visits,
      'slaDeadline': slaDeadline,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}

class CreateReportRequest {
  final String title;
  final String description;
  final String category;
  final String? address;
  final double lat;
  final double lng;
  final List<String>? photos;
  CreateReportRequest({required this.title, required this.description, required this.category, this.address, required this.lat, required this.lng, this.photos});

  factory CreateReportRequest.fromJson(Map<String, dynamic> json) {
    return CreateReportRequest(
      title: json['title'] as String,
      description: json['description'] as String,
      category: json['category'] as String,
      address: json['address'] as String?,
      lat: (json['lat'] as num).toDouble(),
      lng: (json['lng'] as num).toDouble(),
      photos: (json['photos'] as List?)?.map((e) => e as String).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'category': category,
      'address': address,
      'lat': lat,
      'lng': lng,
      'photos': photos,
    };
  }
}

class CaseDetail {
  final String? id;
  final Report? report;
  final VerifikatorCase? verifikatorCase;
  final List<Map<String, dynamic>>? assessments;
  final List<Map<String, dynamic>>? visits;
  final List<AuditEntry>? audit;
  CaseDetail({this.id, this.report, this.verifikatorCase, this.assessments, this.visits, this.audit});

  factory CaseDetail.fromJson(Map<String, dynamic> json) {
    return CaseDetail(
      id: json['id'] as String?,
      report: json['report'] != null ? Report.fromJson(json['report'] as Map<String, dynamic>) : null,
      verifikatorCase: json['verifikatorCase'] != null ? VerifikatorCase.fromJson(json['verifikatorCase'] as Map<String, dynamic>) : null,
      assessments: (json['assessments'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      visits: (json['visits'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      audit: (json['audit'] as List?)?.map((e) => AuditEntry.fromJson(e as Map<String, dynamic>)).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'report': report?.toJson(),
      'verifikatorCase': verifikatorCase?.toJson(),
      'assessments': assessments,
      'visits': visits,
      'audit': audit,
    };
  }
}

class VerifikatorCase {
  final String? id;
  final String? reportId;
  final String? status;
  final String? verifikatorId;
  final String? decision;
  final String? notes;
  final String? createdAt;
  final String? updatedAt;
  VerifikatorCase({this.id, this.reportId, this.status, this.verifikatorId, this.decision, this.notes, this.createdAt, this.updatedAt});

  factory VerifikatorCase.fromJson(Map<String, dynamic> json) {
    return VerifikatorCase(
      id: json['id'] as String?,
      reportId: json['reportId'] as String?,
      status: json['status'] as String?,
      verifikatorId: json['verifikatorId'] as String?,
      decision: json['decision'] as String?,
      notes: json['notes'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'reportId': reportId,
      'status': status,
      'verifikatorId': verifikatorId,
      'decision': decision,
      'notes': notes,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}

class SurveyorTask {
  final String? taskId;
  final String? reportId;
  final String? reportTitle;
  final String? status;
  final String? assignedAt;
  final String? completedAt;
  SurveyorTask({this.taskId, this.reportId, this.reportTitle, this.status, this.assignedAt, this.completedAt});

  factory SurveyorTask.fromJson(Map<String, dynamic> json) {
    return SurveyorTask(
      taskId: json['taskId'] as String?,
      reportId: json['reportId'] as String?,
      reportTitle: json['reportTitle'] as String?,
      status: json['status'] as String?,
      assignedAt: json['assignedAt'] as String?,
      completedAt: json['completedAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'taskId': taskId,
      'reportId': reportId,
      'reportTitle': reportTitle,
      'status': status,
      'assignedAt': assignedAt,
      'completedAt': completedAt,
    };
  }
}

class PetugasTask {
  final String? taskId;
  final String? reportId;
  final String? reportTitle;
  final String? status;
  final List<String>? evidenceUrls;
  final String? assignedAt;
  final String? completedAt;
  PetugasTask({this.taskId, this.reportId, this.reportTitle, this.status, this.evidenceUrls, this.assignedAt, this.completedAt});

  factory PetugasTask.fromJson(Map<String, dynamic> json) {
    return PetugasTask(
      taskId: json['taskId'] as String?,
      reportId: json['reportId'] as String?,
      reportTitle: json['reportTitle'] as String?,
      status: json['status'] as String?,
      evidenceUrls: (json['evidenceUrls'] as List?)?.map((e) => e as String).toList(),
      assignedAt: json['assignedAt'] as String?,
      completedAt: json['completedAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'taskId': taskId,
      'reportId': reportId,
      'reportTitle': reportTitle,
      'status': status,
      'evidenceUrls': evidenceUrls,
      'assignedAt': assignedAt,
      'completedAt': completedAt,
    };
  }
}

class TaskDetail {
  final String? taskId;
  final String? reportId;
  final String? reportTitle;
  final String? description;
  final String? status;
  final int? progress;
  final List<String>? evidenceUrls;
  final Map<String, dynamic>? clarification;
  final String? assignedAt;
  final String? completedAt;
  TaskDetail({this.taskId, this.reportId, this.reportTitle, this.description, this.status, this.progress, this.evidenceUrls, this.clarification, this.assignedAt, this.completedAt});

  factory TaskDetail.fromJson(Map<String, dynamic> json) {
    return TaskDetail(
      taskId: json['taskId'] as String?,
      reportId: json['reportId'] as String?,
      reportTitle: json['reportTitle'] as String?,
      description: json['description'] as String?,
      status: json['status'] as String?,
      progress: json['progress'] as int?,
      evidenceUrls: (json['evidenceUrls'] as List?)?.map((e) => e as String).toList(),
      clarification: json['clarification'] as Map<String, dynamic>?,
      assignedAt: json['assignedAt'] as String?,
      completedAt: json['completedAt'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'taskId': taskId,
      'reportId': reportId,
      'reportTitle': reportTitle,
      'description': description,
      'status': status,
      'progress': progress,
      'evidenceUrls': evidenceUrls,
      'clarification': clarification,
      'assignedAt': assignedAt,
      'completedAt': completedAt,
    };
  }
}

class StatsResponse {
  final int? total;
  final Map<String, dynamic>? byStatus;
  final Map<String, dynamic>? byCategory;
  final int? activeTasks;
  final int? pendingTasks;
  final int? resolvedToday;
  final int? slaAtRisk;
  final int? slaBreached;
  final int? merged;
  final int? separated;
  final int? escalated;
  final String? operatorName;
  final String? region;
  StatsResponse({this.total, this.byStatus, this.byCategory, this.activeTasks, this.pendingTasks, this.resolvedToday, this.slaAtRisk, this.slaBreached, this.merged, this.separated, this.escalated, this.operatorName, this.region});

  factory StatsResponse.fromJson(Map<String, dynamic> json) {
    return StatsResponse(
      total: json['total'] as int?,
      byStatus: json['byStatus'] as Map<String, dynamic>?,
      byCategory: json['byCategory'] as Map<String, dynamic>?,
      activeTasks: json['activeTasks'] as int?,
      pendingTasks: json['pendingTasks'] as int?,
      resolvedToday: json['resolvedToday'] as int?,
      slaAtRisk: json['slaAtRisk'] as int?,
      slaBreached: json['slaBreached'] as int?,
      merged: json['merged'] as int?,
      separated: json['separated'] as int?,
      escalated: json['escalated'] as int?,
      operatorName: json['operatorName'] as String?,
      region: json['region'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'total': total,
      'byStatus': byStatus,
      'byCategory': byCategory,
      'activeTasks': activeTasks,
      'pendingTasks': pendingTasks,
      'resolvedToday': resolvedToday,
      'slaAtRisk': slaAtRisk,
      'slaBreached': slaBreached,
      'merged': merged,
      'separated': separated,
      'escalated': escalated,
      'operatorName': operatorName,
      'region': region,
    };
  }
}
