// AUTO-GENERATED by scripts/codegen.ts — edits will be overwritten

enum ReportStatus {
  draft("draft"),
  submitted("submitted"),
  underReview("under_review"),
  verified("verified"),
  assigned("assigned"),
  inProgress("in_progress"),
  resolved("resolved"),
  closed("closed"),
  rejected("rejected"),
  duplicateMerged("duplicate_merged"),
  needsSurvey("needs_survey"),
  merged("merged"),
  separated("separated"),
  needsCompletion("needs_completion"),
  outOfScope("out_of_scope"),
  pending("pending");
  final String value;
  const ReportStatus(this.value);
  static const allValues = <ReportStatus>[ReportStatus.draft, ReportStatus.submitted, ReportStatus.underReview, ReportStatus.verified, ReportStatus.assigned, ReportStatus.inProgress, ReportStatus.resolved, ReportStatus.closed, ReportStatus.rejected, ReportStatus.duplicateMerged, ReportStatus.needsSurvey, ReportStatus.merged, ReportStatus.separated, ReportStatus.needsCompletion, ReportStatus.outOfScope, ReportStatus.pending];
  static ReportStatus fromJson(String value) => allValues.firstWhere((e) => e.value == value);
}

enum Priority {
  low("low"),
  medium("medium"),
  high("high"),
  critical("critical");
  final String value;
  const Priority(this.value);
  static const allValues = <Priority>[Priority.low, Priority.medium, Priority.high, Priority.critical];
  static Priority fromJson(String value) => allValues.firstWhere((e) => e.value == value);
}

class DuplicateCandidate {
  final String? reportId;
  final String? description;
  final String? status;
  final String? photoUrl;
  final double? distanceM;
  final double? reportCount;
  final double? similarityScore;
  DuplicateCandidate({this.reportId, this.description, this.status, this.photoUrl, this.distanceM, this.reportCount, this.similarityScore});

  factory DuplicateCandidate.fromJson(Map<String, dynamic> json) {
    return DuplicateCandidate(
      reportId: json['report_id']?.toString(),
      description: json['description']?.toString(),
      status: json['status']?.toString(),
      photoUrl: json['photo_url']?.toString(),
      distanceM: (json['distance_m'] as num?)?.toDouble(),
      reportCount: (json['report_count'] as num?)?.toDouble(),
      similarityScore: (json['similarity_score'] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'report_id': reportId,
      'description': description,
      'status': status,
      'photo_url': photoUrl,
      'distance_m': distanceM,
      'report_count': reportCount,
      'similarity_score': similarityScore,
    };
  }
}

class ErrorResponse {
  final String? error;
  final List<Map<String, dynamic>>? details;
  ErrorResponse({this.error, this.details});

  factory ErrorResponse.fromJson(Map<String, dynamic> json) {
    return ErrorResponse(
      error: json['error']?.toString(),
      details: (json['details'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'error': error,
      'details': details,
    };
  }
}

class Pagination {
  final int? page;
  final int? limit;
  final int? total;
  final int? totalPages;
  Pagination({this.page, this.limit, this.total, this.totalPages});

  factory Pagination.fromJson(Map<String, dynamic> json) {
    return Pagination(
      page: json['page'] as int?,
      limit: json['limit'] as int?,
      total: json['total'] as int?,
      totalPages: json['total_pages'] as int?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'page': page,
      'limit': limit,
      'total': total,
      'total_pages': totalPages,
    };
  }
}

class Photo {
  final String? id;
  final String? url;
  final String? thumbnailUrl;
  final String? uploadedAt;
  Photo({this.id, this.url, this.thumbnailUrl, this.uploadedAt});

  factory Photo.fromJson(Map<String, dynamic> json) {
    return Photo(
      id: json['id']?.toString(),
      url: json['url']?.toString(),
      thumbnailUrl: json['thumbnail_url']?.toString(),
      uploadedAt: json['uploaded_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'url': url,
      'thumbnail_url': thumbnailUrl,
      'uploaded_at': uploadedAt,
    };
  }
}

class TimelineEvent {
  final String? id;
  final String? type;
  final String? message;
  final String? timestamp;
  final String? userId;
  TimelineEvent({this.id, this.type, this.message, this.timestamp, this.userId});

  factory TimelineEvent.fromJson(Map<String, dynamic> json) {
    return TimelineEvent(
      id: json['id']?.toString(),
      type: json['type']?.toString(),
      message: json['message']?.toString(),
      timestamp: json['timestamp']?.toString(),
      userId: json['user_id']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'type': type,
      'message': message,
      'timestamp': timestamp,
      'user_id': userId,
    };
  }
}

class Notification {
  final String? id;
  final String? title;
  final String? body;
  final bool? read;
  final String? createdAt;
  Notification({this.id, this.title, this.body, this.read, this.createdAt});

  factory Notification.fromJson(Map<String, dynamic> json) {
    return Notification(
      id: json['id']?.toString(),
      title: json['title']?.toString(),
      body: json['body']?.toString(),
      read: json['read'] as bool?,
      createdAt: json['created_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'body': body,
      'read': read,
      'created_at': createdAt,
    };
  }
}

class AuditEntry {
  final String? id;
  final String? userId;
  final String? action;
  final String? resource;
  final String? resourceId;
  final Map<String, dynamic>? metadata;
  final String? timestamp;
  AuditEntry({this.id, this.userId, this.action, this.resource, this.resourceId, this.metadata, this.timestamp});

  factory AuditEntry.fromJson(Map<String, dynamic> json) {
    return AuditEntry(
      id: json['id']?.toString(),
      userId: json['actor']?.toString(),
      action: json['action']?.toString(),
      resource: json['object_type']?.toString(),
      resourceId: json['object_id']?.toString(),
      metadata: json['metadata'] as Map<String, dynamic>?,
      timestamp: json['created_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'actor': userId,
      'action': action,
      'object_type': resource,
      'object_id': resourceId,
      'metadata': metadata,
      'created_at': timestamp,
    };
  }
}

class Category {
  final String? id;
  final String? name;
  final String? icon;
  final int? reportCount;
  Category({this.id, this.name, this.icon, this.reportCount});

  factory Category.fromJson(Map<String, dynamic> json) {
    return Category(
      id: json['id']?.toString(),
      name: json['name']?.toString(),
      icon: json['icon']?.toString(),
      reportCount: json['report_count'] as int?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'icon': icon,
      'report_count': reportCount,
    };
  }
}

class Unit {
  final String? id;
  final String? name;
  final String? type;
  final String? region;
  Unit({this.id, this.name, this.type, this.region});

  factory Unit.fromJson(Map<String, dynamic> json) {
    return Unit(
      id: json['id']?.toString(),
      name: json['name']?.toString(),
      type: json['type']?.toString(),
      region: json['region']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'type': type,
      'region': region,
    };
  }
}

class SlaConfig {
  final String? id;
  final String? name;
  final int? slaDays;
  final String? priority;
  final bool? isActive;
  final String? createdAt;
  final String? prioritas;
  SlaConfig({this.id, this.name, this.slaDays, this.priority, this.isActive, this.createdAt, this.prioritas});

  factory SlaConfig.fromJson(Map<String, dynamic> json) {
    return SlaConfig(
      id: json['id']?.toString(),
      name: json['kategori_id']?.toString(),
      slaDays: json['jam'] as int?,
      priority: json['prioritas']?.toString(),
      isActive: json['is_active'] as bool?,
      createdAt: json['created_at']?.toString(),
      prioritas: json['prioritas']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'kategori_id': name,
      'jam': slaDays,
      'prioritas': priority,
      'is_active': isActive,
      'created_at': createdAt,
      'prioritas': prioritas,
    };
  }
}

class ChecklistTemplate {
  final String? id;
  final String? name;
  final List<Map<String, dynamic>>? items;
  final String? createdAt;
  ChecklistTemplate({this.id, this.name, this.items, this.createdAt});

  factory ChecklistTemplate.fromJson(Map<String, dynamic> json) {
    return ChecklistTemplate(
      id: json['id']?.toString(),
      name: json['name']?.toString(),
      items: (json['items'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      createdAt: json['created_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'items': items,
      'created_at': createdAt,
    };
  }
}

class PriorityConfig {
  final String? id;
  final String? name;
  final List<Map<String, dynamic>>? rules;
  final bool? isActive;
  final String? createdAt;
  PriorityConfig({this.id, this.name, this.rules, this.isActive, this.createdAt});

  factory PriorityConfig.fromJson(Map<String, dynamic> json) {
    return PriorityConfig(
      id: json['id']?.toString(),
      name: json['name']?.toString(),
      rules: (json['rules'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      isActive: json['is_active'] as bool?,
      createdAt: json['created_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'rules': rules,
      'is_active': isActive,
      'created_at': createdAt,
    };
  }
}

class LoginRequest {
  final String email;
  final String password;
  LoginRequest({required this.email, required this.password});

  factory LoginRequest.fromJson(Map<String, dynamic> json) {
    return LoginRequest(
      email: json['email'].toString(),
      password: json['password'].toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'email': email,
      'password': password,
    };
  }
}

class LoginResponse {
  final String? token;
  final String? refreshToken;
  final User? user;
  LoginResponse({this.token, this.refreshToken, this.user});

  factory LoginResponse.fromJson(Map<String, dynamic> json) {
    return LoginResponse(
      token: json['token']?.toString(),
      refreshToken: json['refresh_token']?.toString(),
      user: json['user'] != null ? User.fromJson(json['user'] as Map<String, dynamic>) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'token': token,
      'refresh_token': refreshToken,
      'user': user?.toJson(),
    };
  }
}

class User {
  final String? id;
  final String? email;
  final String? name;
  final String? role;
  final String? unitId;
  final String? createdAt;
  User({this.id, this.email, this.name, this.role, this.unitId, this.createdAt});

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id']?.toString(),
      email: json['email']?.toString(),
      name: json['name']?.toString(),
      role: json['role']?.toString(),
      unitId: json['unit_id']?.toString(),
      createdAt: json['created_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'name': name,
      'role': role,
      'unit_id': unitId,
      'created_at': createdAt,
    };
  }
}

class UserResponse {
  final String? id;
  final String? email;
  final String? name;
  final String? role;
  final String? unitId;
  final String? createdAt;
  UserResponse({this.id, this.email, this.name, this.role, this.unitId, this.createdAt});

  factory UserResponse.fromJson(Map<String, dynamic> json) {
    return UserResponse(
      id: json['id']?.toString(),
      email: json['email']?.toString(),
      name: json['name']?.toString(),
      role: json['role']?.toString(),
      unitId: json['unit_id']?.toString(),
      createdAt: json['created_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'name': name,
      'role': role,
      'unit_id': unitId,
      'created_at': createdAt,
    };
  }
}

class Report {
  final String? id;
  final String? title;
  final String? description;
  final String? category;
  final ReportStatus? status;
  final Priority? priority;
  final Map<String, dynamic>? location;
  final String? reporterId;
  final List<Photo>? photos;
  final String? slaDeadline;
  final String? createdAt;
  final String? updatedAt;
  final String? mergedInto;
  final String? deadline;
  final int? severity;
  final int? priorityScore;
  Report({this.id, this.title, this.description, this.category, this.status, this.priority, this.location, this.reporterId, this.photos, this.slaDeadline, this.createdAt, this.updatedAt, this.mergedInto, this.deadline, this.severity, this.priorityScore});

  factory Report.fromJson(Map<String, dynamic> json) {
    return Report(
      id: json['id']?.toString(),
      title: json['title']?.toString(),
      description: json['description']?.toString(),
      category: json['category']?.toString(),
      status: json['status'] != null ? ReportStatus.fromJson(json['status'] as String) : null,
      priority: json['priority'] != null ? Priority.fromJson(json['priority'] as String) : null,
      location: json['location'] as Map<String, dynamic>?,
      reporterId: json['reporter_id']?.toString(),
      photos: (json['photos'] as List?)?.map((e) => Photo.fromJson(e as Map<String, dynamic>)).toList(),
      slaDeadline: json['sla_deadline']?.toString(),
      createdAt: json['created_at']?.toString(),
      updatedAt: json['updated_at']?.toString(),
      mergedInto: json['merged_into']?.toString(),
      deadline: json['deadline']?.toString(),
      severity: json['severity'] as int?,
      priorityScore: json['priority_score'] as int?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'category': category,
      'status': status?.value,
      'priority': priority?.value,
      'location': location,
      'reporter_id': reporterId,
      'photos': photos,
      'sla_deadline': slaDeadline,
      'created_at': createdAt,
      'updated_at': updatedAt,
      'merged_into': mergedInto,
      'deadline': deadline,
      'severity': severity,
      'priority_score': priorityScore,
    };
  }
}

class ReportDetail {
  final String? id;
  final String? title;
  final String? description;
  final String? category;
  final ReportStatus? status;
  final Priority? priority;
  final Map<String, dynamic>? location;
  final String? reporterId;
  final List<Photo>? photos;
  final List<Map<String, dynamic>>? assessments;
  final List<Map<String, dynamic>>? visits;
  final String? slaDeadline;
  final String? createdAt;
  final String? updatedAt;
  ReportDetail({this.id, this.title, this.description, this.category, this.status, this.priority, this.location, this.reporterId, this.photos, this.assessments, this.visits, this.slaDeadline, this.createdAt, this.updatedAt});

  factory ReportDetail.fromJson(Map<String, dynamic> json) {
    return ReportDetail(
      id: json['id']?.toString(),
      title: json['title']?.toString(),
      description: json['description']?.toString(),
      category: json['category']?.toString(),
      status: json['status'] != null ? ReportStatus.fromJson(json['status'] as String) : null,
      priority: json['priority'] != null ? Priority.fromJson(json['priority'] as String) : null,
      location: json['location'] as Map<String, dynamic>?,
      reporterId: json['reporter_id']?.toString(),
      photos: (json['photos'] as List?)?.map((e) => Photo.fromJson(e as Map<String, dynamic>)).toList(),
      assessments: (json['assessments'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      visits: (json['visits'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      slaDeadline: json['sla_deadline']?.toString(),
      createdAt: json['created_at']?.toString(),
      updatedAt: json['updated_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'category': category,
      'status': status?.value,
      'priority': priority?.value,
      'location': location,
      'reporter_id': reporterId,
      'photos': photos,
      'assessments': assessments,
      'visits': visits,
      'sla_deadline': slaDeadline,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

class CreateReportRequest {
  final String title;
  final String description;
  final String category;
  final String? address;
  final double lat;
  final double lng;
  final List<String>? photos;
  CreateReportRequest({required this.title, required this.description, required this.category, this.address, required this.lat, required this.lng, this.photos});

  factory CreateReportRequest.fromJson(Map<String, dynamic> json) {
    return CreateReportRequest(
      title: json['title'].toString(),
      description: json['description'].toString(),
      category: json['category'].toString(),
      address: json['address']?.toString(),
      lat: (json['lat'] as num).toDouble(),
      lng: (json['lng'] as num).toDouble(),
      photos: (json['photos'] as List?)?.map((e) => e as String).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'category': category,
      'address': address,
      'lat': lat,
      'lng': lng,
      'photos': photos,
    };
  }
}

class CaseDetail {
  final String? id;
  final Report? report;
  final VerifikatorCase? verifikatorCase;
  final List<Map<String, dynamic>>? assessments;
  final List<Map<String, dynamic>>? visits;
  final List<AuditEntry>? audit;
  final String? status;
  CaseDetail({this.id, this.report, this.verifikatorCase, this.assessments, this.visits, this.audit, this.status});

  factory CaseDetail.fromJson(Map<String, dynamic> json) {
    return CaseDetail(
      id: json['id']?.toString(),
      report: json['report'] != null ? Report.fromJson(json['report'] as Map<String, dynamic>) : null,
      verifikatorCase: json['verifikator_case'] != null ? VerifikatorCase.fromJson(json['verifikator_case'] as Map<String, dynamic>) : null,
      assessments: (json['assessments'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      visits: (json['visits'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      audit: (json['audit'] as List?)?.map((e) => AuditEntry.fromJson(e as Map<String, dynamic>)).toList(),
      status: json['status']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'report': report?.toJson(),
      'verifikator_case': verifikatorCase?.toJson(),
      'assessments': assessments,
      'visits': visits,
      'audit': audit,
      'status': status,
    };
  }
}

class VerifikatorCase {
  final String? id;
  final String? reportId;
  final String? status;
  final String? verifikatorId;
  final String? decision;
  final String? notes;
  final String? createdAt;
  final String? updatedAt;
  VerifikatorCase({this.id, this.reportId, this.status, this.verifikatorId, this.decision, this.notes, this.createdAt, this.updatedAt});

  factory VerifikatorCase.fromJson(Map<String, dynamic> json) {
    return VerifikatorCase(
      id: json['id']?.toString(),
      reportId: json['report_id']?.toString(),
      status: json['status']?.toString(),
      verifikatorId: json['verifikator_id']?.toString(),
      decision: json['decision']?.toString(),
      notes: json['notes']?.toString(),
      createdAt: json['created_at']?.toString(),
      updatedAt: json['updated_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'report_id': reportId,
      'status': status,
      'verifikator_id': verifikatorId,
      'decision': decision,
      'notes': notes,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

class SurveyorTask {
  final String? taskId;
  final String? reportId;
  final String? reportTitle;
  final String? status;
  final String? assignedAt;
  final String? completedAt;
  final String? deadline;
  final String? code;
  final double? slaHoursRemaining;
  final String? priority;
  final double? reportLat;
  final double? reportLng;
  final String? address;
  final String? categoryName;
  SurveyorTask({this.taskId, this.reportId, this.reportTitle, this.status, this.assignedAt, this.completedAt, this.deadline, this.code, this.slaHoursRemaining, this.priority, this.reportLat, this.reportLng, this.address, this.categoryName});

  factory SurveyorTask.fromJson(Map<String, dynamic> json) {
    return SurveyorTask(
      taskId: json['id']?.toString(),
      reportId: json['report_id']?.toString(),
      reportTitle: json['report_description']?.toString(),
      status: json['status']?.toString(),
      assignedAt: json['accepted_at']?.toString(),
      completedAt: json['completed_at']?.toString(),
      deadline: json['deadline']?.toString(),
      code: json['code']?.toString(),
      slaHoursRemaining: (json['sla_hours_remaining'] as num?)?.toDouble(),
      priority: json['priority']?.toString(),
      reportLat: (json['lat'] as num?)?.toDouble(),
      reportLng: (json['lng'] as num?)?.toDouble(),
      address: json['address']?.toString(),
      categoryName: json['category_name']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': taskId,
      'report_id': reportId,
      'report_description': reportTitle,
      'status': status,
      'accepted_at': assignedAt,
      'completed_at': completedAt,
      'deadline': deadline,
      'code': code,
      'sla_hours_remaining': slaHoursRemaining,
      'priority': priority,
      'lat': reportLat,
      'lng': reportLng,
      'address': address,
      'category_name': categoryName,
    };
  }
}

class PetugasTask {
  final String? taskId;
  final String? reportId;
  final String? reportTitle;
  final String? status;
  final List<String>? evidenceUrls;
  final String? assignedAt;
  final String? completedAt;
  PetugasTask({this.taskId, this.reportId, this.reportTitle, this.status, this.evidenceUrls, this.assignedAt, this.completedAt});

  factory PetugasTask.fromJson(Map<String, dynamic> json) {
    return PetugasTask(
      taskId: json['id']?.toString(),
      reportId: json['report_id']?.toString(),
      reportTitle: json['report_description']?.toString(),
      status: json['status']?.toString(),
      evidenceUrls: (json['photo_urls'] as List?)?.map((e) => e as String).toList(),
      assignedAt: json['accepted_at']?.toString(),
      completedAt: json['completed_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': taskId,
      'report_id': reportId,
      'report_description': reportTitle,
      'status': status,
      'photo_urls': evidenceUrls,
      'accepted_at': assignedAt,
      'completed_at': completedAt,
    };
  }
}

class TaskDetail {
  final String? taskId;
  final String? reportId;
  final String? reportTitle;
  final String? description;
  final String? status;
  final int? progress;
  final List<Map<String, dynamic>>? evidenceUrls;
  final List<Map<String, dynamic>>? clarification;
  final String? assignedAt;
  final String? completedAt;
  TaskDetail({this.taskId, this.reportId, this.reportTitle, this.description, this.status, this.progress, this.evidenceUrls, this.clarification, this.assignedAt, this.completedAt});

  factory TaskDetail.fromJson(Map<String, dynamic> json) {
    return TaskDetail(
      taskId: (json['task'] as Map<String, dynamic>?)?['id']?.toString(),
      reportId: (json['task'] as Map<String, dynamic>?)?['report_id']?.toString(),
      reportTitle: (json['task'] as Map<String, dynamic>?)?['report_description']?.toString(),
      description: (json['task'] as Map<String, dynamic>?)?['report_description']?.toString(),
      status: (json['task'] as Map<String, dynamic>?)?['status']?.toString(),
      progress: (json['task'] as Map<String, dynamic>?)?['progress_percent'] as int?,
      evidenceUrls: (json['evidence'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      clarification: (json['clarifications'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      assignedAt: (json['task'] as Map<String, dynamic>?)?['accepted_at']?.toString(),
      completedAt: (json['task'] as Map<String, dynamic>?)?['completed_at']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'evidence': evidenceUrls,
      'clarifications': clarification,
    };
  }
}

class StatsResponse {
  final int? total;
  final Map<String, dynamic>? byStatus;
  final List<Map<String, dynamic>>? byCategory;
  final int? activeTasks;
  final int? pendingTasks;
  final int? resolvedToday;
  final int? slaAtRisk;
  final int? slaBreached;
  final int? merged;
  final int? separated;
  final int? escalated;
  final String? operatorName;
  final String? region;
  final Map<String, dynamic>? dashboard;
  StatsResponse({this.total, this.byStatus, this.byCategory, this.activeTasks, this.pendingTasks, this.resolvedToday, this.slaAtRisk, this.slaBreached, this.merged, this.separated, this.escalated, this.operatorName, this.region, this.dashboard});

  factory StatsResponse.fromJson(Map<String, dynamic> json) {
    return StatsResponse(
      total: json['total'] as int?,
      byStatus: json['by_status'] as Map<String, dynamic>?,
      byCategory: (json['by_category'] as List?)?.map((e) => e as Map<String, dynamic>).toList(),
      activeTasks: (json['queue_counts'] as Map<String, dynamic>?)?['needs_completion'] as int?,
      pendingTasks: (json['queue_counts'] as Map<String, dynamic>?)?['needs_verification'] as int?,
      resolvedToday: (json['by_status'] as Map<String, dynamic>?)?['resolved'] as int?,
      slaAtRisk: json['sla_at_risk'] as int?,
      slaBreached: json['sla_breached'] as int?,
      merged: json['merged'] as int?,
      separated: json['separated'] as int?,
      escalated: json['escalated'] as int?,
      operatorName: json['operator_name']?.toString(),
      region: json['region']?.toString(),
      dashboard: json['dashboard'] as Map<String, dynamic>?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'total': total,
      'by_status': byStatus,
      'by_category': byCategory,
      'sla_at_risk': slaAtRisk,
      'sla_breached': slaBreached,
      'merged': merged,
      'separated': separated,
      'escalated': escalated,
      'operator_name': operatorName,
      'region': region,
      'dashboard': dashboard,
    };
  }
}
